---
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: 'gitlab'
    hostname: '$GITLAB_DOMAIN'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://$GITLAB_DOMAIN'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'exim'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = 'exim'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
    ports:
      #- '80:80'
      #- '443:443'
      - '22:22'
    labels:
      - "traefik.frontend.rule=Host:$GITLAB_DOMAIN"
      - "traefik.docker.network=gitlab"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.protocol=http"
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '$GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner'
      - '$GITLAB_HOME/gitlab-runner/data:/home/gitlab_ci_multi_runner/data'
    environment:
      - CI_SERVER_URL=https://$GITLAB_DOMAIN/ci
    networks:
      - gitlab
  exim:
    image: tianon/exim4
    restart: always
    container_name: 'exim'
    hostname: '$GITLAB_DOMAIN'
    ports:
      - '25:25'
    networks:
      - gitlab
  traefik:
    image: traefik
    command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    restart: always
    networks:
    - gitlab
    ports:
    - "80:80"
    - "443:443"
    - "9000:9000"  # exposes the Traefik web UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # So that Traefik can listen to the Docker events
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    container_name: traefik
networks:
  gitlab:
    name: gitlab-network
